# Banking Control Panel API

###
# group: Auth
# @name Register
POST http://localhost:5147/api/auth/register
Content-Type: application/json

{
  "email": "Test@example.com",
  "password": "Password123!",
  "role": "Admin"
}

###
# group: Auth
# @name Login
POST http://localhost:5147/api/auth/login
Content-Type: application/json

{
  "email": "Test@example.com",
  "password": "Password123!"
}

###
# group: Clients
# @name Get Clients
GET http://localhost:5147/api/clients?
    filter=John&
    sort=asc&
    page=1&
    pageSize=10

###
# group: Clients
# @name Get Client by ID
GET http://localhost:5147/api/clients/{{id}}

###
# group: Clients
# @name Add Client
POST http://localhost:5147/api/clients
Content-Type: application/json

{
  "firstName": "Johnx",
  "lastName": "Doex",
  "email": "john.doe@example.com",
  "personalId": "12345678901",
  "profilePhoto": "base64string",
  "mobileNumber": "+1234567890",
  "Gender": "Male",
  "address": {  
    "country": "Country",
    "city": "City",
    "street": "Street",
    "zipCode": "00000"
  },
  "accounts": [
    {
      "accountNumber": "123456",
      "balance": 1000.00
    }
  ]
}

###
# group: Clients
# @name Update Client
PUT http://localhost:5147/api/clients/{{id_1}}
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "personalId": "12345678901",
  "profilePhoto": "base64string",
  "mobileNumber": "+1234567890",
  "sex": "Male",
  "address": {
    "country": "Country",
    "city": "City",
    "street": "Street",
    "zipCode": "00000"
  },
  "accounts": [
    {
      "accountNumber": "123456",
      "balance": 1000.00
    }
  ]
}

###
# group: Clients
# @name Delete Client
DELETE http://localhost:5147/api/clients/{{id_2}}